### ISSUE TITLE
Version 1.1.0 has build break

### ISSUE THREAD

**Issue by codesForLiving** [commonsguy/cwac-wakeful#26] opened 2016-11-22 12:13 UTC

**Comment by commonsguy** [comment] 2016-11-22 12:17
Closing as lacking any detail, and therefore being unreproducible.

**Closed by commonsguy** 2016-11-22 12:17 UTC

**Comment by codesForLiving** [comment] 2016-11-22 12:19
@commonsguy https://jitpack.io/#commonsguy/cwac-wakeful/ see the report against the version number to see the build break. If the report is not available, click on "get it" button, it will try to build and will fail, and then you can have the report.

**Comment by commonsguy** [comment] 2016-11-22 12:24
I do not use jitpack.io. I distribute this library by other means, described in the project README.

That log shows that jitpack is trying to use Gradle 2.7 rather than 2.10. My project requests 2.10 via `gradle/wrapper/gradle-wrapper.properties`. I have no idea why jitpack.io is trying to use 2.7. More importantly, debugging jitpack.io is not my problem.

**Comment by codesForLiving** [comment] 2016-11-22 12:31
When I try to use 
```
compile 'com.github.commonsguy:cwac-wakeful:v1.1.0'
compile 'com.github.commonsguy:cwac-wakeful:v1.0.5'
```
Android studio cannot find the artifacts. I tried to see why this is happening on jitpack.io, and build for these versions were failing.

My repository configuration

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by commonsguy** [comment] 2016-11-22 12:54
> Android studio cannot find the artifacts

You need to add the entry to your `repositories` closure as is documented in [the `README`](https://github.com/commonsguy/cwac-wakeful).

**Comment by codesForLiving** [comment] 2016-11-22 13:04
```
allprojects {
    repositories {

        jcenter()
        maven {
            url "https://s3.amazonaws.com/repo.commonsware.com"
        }
        maven { url "https://jitpack.io" }
    }
}
```

I have included it. It still fails for compile time dependency

`compile 'com.github.commonsguy:cwac-wakeful:v1.1.0'`
`compile 'com.github.commonsguy:cwac-wakeful:v1.0.5'`

It works for 

`compile 'com.github.commonsguy:cwac-wakeful:v1.0.4'`

**Comment by commonsguy** [comment] 2016-11-22 13:11
v1.0.5 and v1.1.0 are in the Maven repo, along with v1.0.4 and older versions. However, since you tried (and failed) to get them earlier, Gradle probably will not try again for 24 hours. If you are comfortable with command-line builds, use `--refresh-dependencies` on some Gradle task to get Gradle to try again to load the dependencies.
